name: Deploy to Server

on:
  push:
    branches:
      - main
jobs:
  push-to-registry:
    name: Push Docker image to registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: poposnek/personal-website
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestations
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/poposnek/personal-website
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true